apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: mirage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: ghcr.io/ahs0042/mirage-api-gateway:v2
          ports:
            - containerPort: 8000
          env:
            - name: AUTH_SERVICE_URL
              value: "http://auth-service:8001"
            - name: CATALOG_SERVICE_URL
              value: "http://catalog-service:8002"
            - name: RECOMMENDATION_SERVICE_URL
              value: "http://recommendation-service:8003"
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 15
