apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: mirage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: ghcr.io/ahs0042/mirage-auth-service:latest
          ports:
            - containerPort: 8001
