apiVersion: v1
kind: Service
metadata:
  name: recommendation-service
  namespace: mirage
spec:
  selector:
    app: recommendation-service
  ports:
    - protocol: TCP
      port: 8003
      targetPort: 8003
        readinessProbe:
            httpGet:
              path: /health
              port: 8003
            initialDelaySeconds: 5
            periodSeconds: 10

        livenessProbe:
            httpGet:
              path: /health
              port: 8003
            initialDelaySeconds: 10
            periodSeconds: 15
