name: Mirage CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          - name: auth-service
            path: ./services/auth-service
          - name: catalog-service
            path: ./services/catalog-service
          - name: recommendation-service
            path: ./services/recommendation-service
          - name: api-gateway
            path: ./api-gateway

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.service.path }}
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/mirage-${{ matrix.service.name }}:latest
